### ISSUE TITLE
mac os build broken

### ISSUE THREAD

**Issue by zonca** [conda-forge/healpy-feedstock#15]
Hi @conda-forge/core,

Please move the mac os build of my package `osx-64/healpy-1.12.2-py36h7127e17_0.tar.bz2`
 from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

It doesn't even import, not sure how circleci uploaded it to anaconda.org as it failed the unit tests.

**Comment by dfm** [comment]
Yep! Definitely broken 😄

**Comment by mwcraig** [comment]
Sorry for the delay -- which versions do you want removed? Just that specific build for mac or all builds for mac that are 1.12.x or something else?

**Comment by zonca** [comment]
just that one, it is the only one that was built for 1.12.x

**Comment by mwcraig** [comment]
Done!
