### ISSUE TITLE
Healpy on conda is out of date.

### ISSUE THREAD

**Issue by janerigby** [conda-forge/healpy-feedstock#2]
The latest version of healpy (1.10.X)  is not accessible via conda.  Only 1.9.1 is available.

I opened a ticket with OpenAstronomy:
   https://github.com/OpenAstronomy/conda-channel/issues/34#issuecomment-303777596

They say that the problem is with conda-forge.  Can we please get conda-forge to see the latest version of healpy?

**Comment by zonca** [comment]
I tried submitting a Pull Request to conda forge, https://github.com/conda-forge/healpy-feedstock/pull/3, let's see if it builds correctly
